### ISSUE TITLE
Add mipmap support

### ISSUE THREAD

**Issue by F3000** [kefir500/apk-icon-editor#63] opened 2018-03-22 22:18 UTC
Apps that where build withe newer Version of Android Studio doesnt show the pictures/Logos. 

I have tried following apps:
https://simplemobiletools.github.io/

Workaround:
Copy the pictures from mipmap-xxx -> drawable-xxx 

Maybe the author need to adjust the code of the tool :)

**Comment by kefir500** [comment] 2018-03-23 09:18
Could you provide the (link to the) APK?

In fact, both `drawable` and `mipmap` resource directories are supported. Most likely, the problem is the [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html) introduced in the Android 8. This issue can be tracked [here](https://github.com/kefir500/apk-icon-editor/issues/62).

**Comment by kefir500** [comment] 2018-03-23 15:08
In fact, both `drawable` and `mipmap` resource directories are supported. The problem is the [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html) introduced in the Android 8. This issue can be tracked [here](https://github.com/kefir500/apk-icon-editor/issues/62); closing this one as duplicate.

**Closed by kefir500** 2018-03-23 15:08 UTC
