### ISSUE TITLE
Png error

### ISSUE THREAD

**Issue by hokienhoa** [kefir500/apk-icon-editor#55] opened 2017-02-12 02:35 UTC
I tried to add banner and change icon to the apk file, when i try to save the path always show png error, dont get it can you help me out

**Comment by kefir500** [comment] 2017-02-12 05:53
- Repeat the steps until you get the error.
- Click `Help` –> `Logs` –> `Open Log Directory` (or simply press <kbd>Ctrl</kbd> + <kbd>L</kbd>).
- Provide the logfile (or its contents).

Also if it is possible, provide the APK itself.

**Comment by hokienhoa** [comment] 2017-02-12 21:28
[apk-icon-editor.zip](https://github.com/kefir500/apk-icon-editor/files/769646/apk-icon-editor.zip)

**Comment by kefir500** [comment] 2017-02-14 09:46
- Does this happen when you **only** change icon (without adding a banner)?
- Does this happen with **any** APK or just with a particular one?
- If only the specific APK is affected, it is hard to tell the reason of this issue without examining the APK itself.

**Comment by hokienhoa** [comment] 2017-02-14 12:56
Only for banner for all apk files
When i change name and icon for apk files all of them went through 
Only when i add banner to apk files

**Comment by kefir500** [comment] 2017-02-15 13:09
This issue is happening due to the presence of the empty `android:banner` attribute in the APK manifest file. However, such behavior occurs only in the "SPMC" APK, so I'm not sure why you wrote that this happens to any APK.

Anyway, try this pre-release ([APK icon Editor 1.7.1-PRE](https://drive.google.com/open?id=0B64chMV33kanNmVDRlJIVDJKUXc)) and let me know if the problem is fixed.

**Comment by hokienhoa** [comment] 2017-02-15 16:30
It worked now , thanks for the support

**Comment by kefir500** [comment] 2017-02-15 16:37
Thanks for the feedback.  
The official updated version will be released soon,
How can I mention you in the APK Icon Editor **About** section (by your full name, nickname, etc.)?

**Comment by hokienhoa** [comment] 2017-02-15 17:24
Mr K

Sent from kinwa ho

On Feb 15, 2017, at 11:38 AM, Alexander Gorishnyak <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the feedback.
The official updated version will be released soon,
How can I mention you in the APK Icon Editor About section (by your full name, nickname, etc.)?

**Closed** 2017-02-16 06:25 UTC
Labels: apk, bug
